Repository apple/swift-nio-imap, pull requests merged in 2025-05, with the labels that each got.

#791 Add MessageIdentifierSet.suffix overload
  Sources/NIOIMAPCore/Grammar/UID/MessageIdentifierSet.swift
  Tests/NIOIMAPCoreTests/Grammar/MessageIdentifierSet+Tests.swift
Labels: semver/none

#789 Pass response parser options into IMAPClientHandler.init
  Sources/NIOIMAP/Coders/IMAPClientHandler.swift
  Sources/NIOIMAP/Coders/ResponseDecoder.swift
  Sources/NIOIMAPCore/Parser/ResponseParser.swift
  Tests/NIOIMAPCoreTests/Parser/ResponseParser+Tests.swift
Labels: ⚠️ semver/major

#793 Rename → IMAPClientHandler.Message
  Sources/NIOIMAP/Coders/IMAPClientHandler.swift
  Tests/NIOIMAPTests/Coders/IMAPClientHandlerTests.swift
Labels: ⚠️ semver/major

#792 Add additional test case for encoding `\` and `"`
  Tests/NIOIMAPCoreTests/Grammar/CommandType/CommandType+Tests.swift
Labels: semver/none

#794 Improve (pre-calculated) hash of MailboxName
  Sources/NIOIMAPCore/Grammar/Mailbox/MailboxName.swift
  Tests/NIOIMAPCoreTests/Grammar/Mailbox/MailboxName+Tests.swift
Labels: semver/none

#795 RFC 8474 - IMAP Extension for Object Identifiers
  EXTENSIONS.md
  Sources/NIOIMAPCore/Grammar/Capability.swift
  Sources/NIOIMAPCore/Grammar/FetchAttribute.swift
  Sources/NIOIMAPCore/Grammar/Mailbox/MailboxAttribute.swift
  Sources/NIOIMAPCore/Grammar/Mailbox/MailboxID.swift
  Sources/NIOIMAPCore/Grammar/Message/EmailID.swift
  Sources/NIOIMAPCore/Grammar/Message/MessageAttributes.swift
  Sources/NIOIMAPCore/Grammar/Message/ThreadID.swift
  Sources/NIOIMAPCore/Grammar/ObjectID.swift
  Sources/NIOIMAPCore/Grammar/Response/ResponseTextCode.swift
  Sources/NIOIMAPCore/Grammar/Search/SearchKey.swift
  Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Fetch.swift
  Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Mailbox.swift
  Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Message.swift
  Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Response.swift
  Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Search.swift
  Sources/NIOIMAPCore/Parser/Grammar/GrammarParser.swift
  Sources/NIOIMAPCore/Parser/UInt8+ParseTypeMembership.swift
  Sources/NIOIMAPCore/Pipelining.swift
  Tests/NIOIMAPCoreTests/Grammar/Capability+Tests.swift
  Tests/NIOIMAPCoreTests/Grammar/FetchAttributeTests.swift
  Tests/NIOIMAPCoreTests/Grammar/Mailbox/MailboxAttribute+Tests.swift
  Tests/NIOIMAPCoreTests/Grammar/Message/MessageAtributesTests.swift
  Tests/NIOIMAPCoreTests/Grammar/Response/ResponseTextCodeTests.swift
  Tests/NIOIMAPCoreTests/Grammar/Search/SearchKeyTests.swift
  Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Fetch+Tests.swift
  Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Message+Tests.swift
  Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Response+Tests.swift
  Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Search+Tests.swift
  Tests/NIOIMAPCoreTests/Parser/IMAPParserTests.swift
Labels: ⚠️ semver/major

#797 Fix encoding of UID EXPUNGE
  Sources/NIOIMAPCore/Grammar/Command/Command.swift
  Tests/NIOIMAPCoreTests/Grammar/CommandType/CommandType+Tests.swift
Labels: semver/none

#777 UIDBATCHES Extension
  EXTENSIONS.md
  Sources/NIOIMAPCore/Grammar/Capability.swift
  Sources/NIOIMAPCore/Grammar/Command/Command.swift
  Sources/NIOIMAPCore/Grammar/Mailbox/MailboxData.swift
  Sources/NIOIMAPCore/Grammar/Response/UIDBatchesResponse.swift
  Sources/NIOIMAPCore/Grammar/UID/MessageIdentifierRange.swift
  Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Commands.swift
  Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Mailbox.swift
  Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Response.swift
  Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Search.swift
  Sources/NIOIMAPCore/Parser/Grammar/GrammarParser+Sequence.swift
  Sources/NIOIMAPCore/Parser/Grammar/GrammarParser.swift
  Sources/NIOIMAPCore/Pipelining.swift
  Tests/NIOIMAPCoreTests/Grammar/CommandType/CommandType+Tests.swift
  Tests/NIOIMAPCoreTests/Grammar/Mailbox/MailboxData+Tests.swift
  Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Commands+Tests.swift
  Tests/NIOIMAPCoreTests/Parser/Grammar/GrammarParser+Mailbox+Tests.swift
  Tests/NIOIMAPCoreTests/Parser/IMAPParserTests.swift
  Tests/NIOIMAPCoreTests/PipeliningTests.swift
Labels: kind/enhancement, ⚠️ semver/major
